### ISSUE TITLE
a question about (im)possible feature: responsive views setup?

### ISSUE THREAD

**Issue by pejotigrek** [nervetattoo/themable-grid#2]
I probably know the answer already [= it is not possible ;)] but I need to ask anyway.

### here's my scenario:
my main lovelace-ui is prepared in a way that every "basic" view [without expanded rows, opened popup windows etc.] fits the screen without scrolling - and that's why there are 6 main views with one column each - I prefer to use view/tab buttons to switch screens that scrolling it up/down. every view has it's own yaml and I'm using _!include_ to join those yamls into one. when going to dashboard on desktop, I'm using a secondary lovelace-ui config, that is including those view-yamls in a way that instead of 6 views, I've got only 2 views, but with 3 colums each [quick yaml examples below].

this is working fine for me, and I'm good as it is [thanks to a possibility to set different default dashboards for different devices], but seeing your themable-grid I'm wondering if it could be expanded to be used with views.

### the question:
is it possible to add a feature to your themable-grid so my scenario could use only one lovelace-ui file but with the very same output as my current two files? so the breaking-points would be checked before rendering views, and then they would be configured accordingly [something like moving the breaking-points config up in the configuration tree, and giving them "views" parameter instead of "columns"].

### quick yaml examples as promised:

**ui.lovelace.yaml**

```
title: mobile config
views:
- title: 1
  cards: !include /config/lovelace/1.yaml
- title: 2
  cards: !include /config/lovelace/2.yaml
- title: 3
  cards: !include /config/lovelace/3.yaml
[...and so on]
- title: 6
  cards: !include /config/lovelace/6.yaml
```
**ui.lovelace_desktop.yaml**

```
title: desktop config
views:
- title: 1+2+3
  cards:
  - type: vertical-stack
    cards: !include /config/lovelace/1.yaml
  - type: vertical-stack
    cards: !include /config/lovelace/2.yaml
  - type: vertical-stack
    cards: !include /config/lovelace/3.yaml
- title: 4+5+6
  cards:
  - type: vertical-stack
    cards: !include /config/lovelace/4.yaml
  - type: vertical-stack
    cards: !include /config/lovelace/5.yaml
  - type: vertical-stack
    cards: !include /config/lovelace/6.yaml
```
