### ISSUE TITLE
Breakpoints Don't Work Post v2.0.1

### ISSUE THREAD

**Issue by akeslo** [nervetattoo/themable-grid#7]
I'm running v2.0.1 as I can't seem to get breakpoints working in anything past this version.  Is this a known issue?

Thanks!

![image](https://user-images.githubusercontent.com/3003773/200187282-cf8023d6-4149-434c-bfeb-0988993ddd84.png)

**Comment by mattydebie** [comment]
@akeslo Seems to work again on 2022.12.0

**Comment by The-Croz** [comment]
Definitely still occurring on 2023.1. Had to revert to v2.0.1 to get the breakpoints to work again

**Comment by akeslo** [comment]
> o v2.0.1 to get the breakpoints to work

Yeah I can't upgrade past v2.0.1 - I just keep it on this version as it's totally not fixed in anything above.

**Comment by CumpsD** [comment]
Probably because this of this commit: https://github.com/nervetattoo/themable-grid/commit/93b9bf4c69065a122334034b33d54a872c372e06
Where your custom config gets overwritten by the default config

**Comment by CumpsD** [comment]
This is the default, which will overwrite what you specify:

```js
export default {
  padding: 0,
  gap: '8px',
  breakpoints: [
    {
      name: 'mobile',
      mq: '(max-width: 767px)',
      columns: 1,
    }, {
      name: 'tablet',
      mq: '(min-width: 768px) and (max-width: 1023px)',
      columns: 2,
    }, {
      name: 'desktop',
      mq: '(min-width: 1024px)',
      columns: 3,
    }
  ]
}
```

However, from rule 4 on, there is nothing to overwrite, so this config works:

```yaml
type: custom:auto-entities
filter:
  include:
    - integration: shelly
      domain: switch
      options:
        type: custom:mushroom-entity-card
sort:
  method: friendly_name
show_empty: true
card_param: cards
card:
  type: custom:themable-grid
  padding: 0
  gap: 8px
  breakpoints:
    - name: mobile
      mq: '(max-width: 767px)'
      columns: 1
    - name: tablet
      mq: '(min-width: 768px) and (max-width: 1023px)'
      columns: 2
    - name: desktop-small
      mq: '(min-width: 1024px)'
      columns: 3
    - name: desktop
      mq: '(min-width: 1240px)'
      columns: 4
    - name: desktop-wide
      mq: '(min-width: 1600px)'
      columns: 5
```
